services:
  - type: worker
    name: sector-economy
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: MONGO_URI
        sync: false
